services:
  prometheus:
    image: prom/prometheus
    container_name: prometheus_ecom
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
  grafana:
    image: grafana/grafana
    container_name: grafana_ecom
    ports:
      - "3000:3000"