logging:
  level:
    root: DEBUG
debug: false
spring:
  redis:
    host: localhost
    port: 6379
    database: 1
db:
  jdbcUrl: jdbc:postgresql://localhost:8844/ecom
  username: usr
  password: pass
app:
  port: 7003
  verify:
    ttl: 600
    retry-timeout: 60
  token:
    publicKeyPath: .local/public_key.pem
    privateKeyPath: .local/private_key.pem
    access-ttl: 3600
    refresh-ttl: 36000
